### ISSUE TITLE
P1 Mode signal 11 on Ubuntu 19.04

### ISSUE THREAD

**Issue by katakombi** [indigo-dc/udocker#192]
When I run udocker from Ubuntu 19.04 with kernel 5.0 I get a Signal 11:

```
./udocker pull alpine:latest
./udocker create --name=a alpine:latest
./udocker run a sh
proot info: vpid 1: terminated with signal 11
```
This happens when P1 mode is being used. P2 still seems to work fine when forced using 
```
export PROOT_NO_SECCOMP=1
```

Edit: there might be related issues https://github.com/proot-me/proot/issues/106
Could someone please confirm or give further details?

**Comment by jorge-lip** [comment]
This issue seems fixed in the devel branch.

**Comment by katakombi** [comment]
Did you update the proot static binary? Gonna recheck...

**Comment by katakombi** [comment]
Confirmed to be fixed! Congrats & thanks! I'd just be interested if the issue was with proot after all...

**Comment by jorge-lip** [comment]
Yes it was recompiled. The tarball used by the devel branch is newer.

**Comment by katakombi** [comment]
Alas, proot didn't solve the underlying bug (probably proot-me/proot#106)
This issue can still occur on other kernels/distros. I found it on Fedora 31 with kernel 5.3.11. Useless to open issues for udocker, just adding this as a note!

**Comment by jorge-lip** [comment]
Hi,
Can you try with the latest development version

**Comment by katakombi** [comment]
I don't have my VM with Fedora 31 any longer. So I'd test it but it might take a while...

**Comment by fireflyHunter** [comment]
I am experiencing the same issue here with latest udocker, tried different images but all fail.
